# Generated by Django 3.1.3 on 2023-04-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=50)),
                ('nombreAbogado', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
